### ISSUE TITLE
Minor bug when reading by timestamps

### ISSUE THREAD

**Issue by dancrepeau** [msel-source/pymef#26] opened 2021-07-30 16:11 UTC
It was reported to Mayo by an external user that when reading channel data by specifying timestamps, that there are inconsistencies depending on how the data is read.  For example, when reading data in the following ways:

        chunk_usec = 60000000      # 1 minute
        data1 = ms.read_ts_channels_uutc(name, (uutc1,uutc1+chunk_usec),out_nans=True)
        data2 = ms.read_ts_channels_uutc(name, (uutc1+chunk_usec,uutc1+2*chunk_usec),out_nans=True)
        data_e  = ms.read_ts_channels_uutc(name, (uutc1,uutc1+2*chunk_usec),out_nans=True)

This case reads the first two minutes of the channel, in one minute chunks, then in a single 2 minute chunk.  In this case if you concat data1 and data2, it should be identical to data_e.  But in fact there are some small differences.  This discrepency is true as of version 1.3.0 of pymef.
    
So... in the case above, the issue seems to be that the first block decoded into data2 has all of it's samples shifted by one place.  Assuming that the chunk size is a multiple of the sampling frequency, that shifting appears to be a bug.

Investigating it, the problem is that the first block is manually placed into a buffer, since it is often the case that entire block is not needed.  So an offset is calculated: the start time of the block minus the start time of the desired buffer.  Any samples that correspond to a negative offset are discarded.  Since the buffer elements correspond to samples at the sampling frequency of the recording, rounding has to be done.  The bug is that rounding negative numbers needs to be done differently than rounding positive numbers:

if ((block_start_time_offset - start_time) >= 0)
    offset_into_output_buffer = (si4) ((((block_start_time - start_time) / 1000000.0) * channel->metadata.time_series_section_2->sampling_frequency) + 0.5);
else
    offset_into_output_buffer = (si4) ((((block_start_time - start_time) / 1000000.0) * channel->metadata.time_series_section_2->sampling_frequency) - 0.5);
    
This change for the first block decoded (this situation should never happen in the last block decoded, but probably best to make the change for that as well, to account for possible out-of-order-blocks).

**Comment by dancrepeau** [comment] 2021-07-30 17:09
I will check-in the fixed version of pymef3_file.c, if no one objects.

**Comment by cimbi** [comment] 2021-08-02 23:05
to be clear, the commit e824bfe6 fixes this issue?

**Comment by dancrepeau** [comment] 2021-08-02 23:56
Correct - and it also fixes the other issue (nans when reading by sample).  Both were fixed in the same commit.

**Comment by cimbi** [comment] 2021-08-03 07:00
Fixed by e824bfe

**Comment by cimbi** [comment] 2021-08-03 08:20
The tests started failing after this correction. The problem is when the user specifies uutc time in a discontinuity (either start or stop). 

When uutc start is in a discontinuity the number of NaNs should be 2500 and number of samples 2499 (end time is not inclusive) but after the commit this is swapped.

Code for testing start uutc in discontinuity
```python
discont_end_time = int(self.end_time + (1e6*self.secs_to_append)
                               + int(1e6*self.discont_length))

start = int(discont_end_time - 5e5)
end = int(discont_end_time + 5e5)

data = self.ms.read_ts_channels_uutc(self.ts_channel,
                                     [start, end])

# Check for the number of NaNs
N_nans = (5e5 / 1e6) * self.sampling_frequency
read_N_nans = np.sum(np.isnan(data))

self.assertEqual(N_nans, read_N_nans)
```

When the uutc end is in a discontinuity the number of samples should be 2500 and number of NaNs 2499 (end time not inclusive). Again, swapped after the commit.

Code for testing end uutc in discontinuity:
```python
discont_start_time = int(self.end_time) + int(1e6*self.secs_to_append)

start = int(discont_start_time - 5e5)
end = int(discont_start_time + 5e5)

data = self.ms.read_ts_channels_uutc(self.ts_channel,
                                     [start, end])

# Check for the number of NaNs
N_nans = (5e5 / 1e6) * self.sampling_frequency
N_nans -= 1  # End is not inclusive
read_N_nans = np.sum(np.isnan(data))
```

Is this the behavior we want? To me it seems it should be the other way around.

**Comment by dancrepeau** [comment] 2021-08-03 16:37
I took a look at pymef_test.py, and the resulting .mefd directory (creating in a temp file, I had to pause the test script in order to read the files before they disappeared).  What I'm seeing in the actual .timd file is two segments, the first is 15 seconds long and the second is 5 seconds.  The first begins at 946684800 (utc) and goes until ...815, and the second begins at ...817 and goes until ...822.  So immediately I think something is wrong - the secs_to_write is 10, and secs_to_append is 5.  I'm still a bit new to python - but if I'm understanding it correctly, on line 220 of the script it is concat'ing raw_data and raw_data_to_append and calling that raw_data_seg 1.  That would explain why the first segment is 15 seconds, and not 10.

Anyway, the upshot is that back in test_start_uutc_in_discontinuity, the discont_end_time (946684817) is actually the start time of the discontinuity, since the extra 5 seconds were added to the first segment, I think that's shifting everything over.

**Comment by dancrepeau** [comment] 2021-08-04 15:24
Deleting my last comment - I can see that segment 1 in the test script contains 15 seconds, 10 seconds of the original write plus 5 seconds of append.  Then a 2 second gap, then 5 more seconds in segment 2.  I agree with your analysis that there should be an extra NaN in the test results... I will try to figure out what is going on.

**Comment by dancrepeau** [comment] 2021-08-04 16:14
I just fixed a bug which makes one of the tests pass now (the first test, test_start_uutc_in_discontinuity).  That was just a simple uninitialized variable bug.

But I still can't get the second test to pass.  In the test, it is expecting 2500 samples and 2499 NaNs.  I'm not sure how that's possible, since the total samples returned from the read command is 5000 (unless we're expecting 2501 actual samples?).  I think it should be 2500 of real samples and 2500 NaN's.  When I comment out the "N_nans -= 1" line, that test passes.

So I'll check in the fix for the first test, which is a definite bug, no doubt about that.

**Comment by dancrepeau** [comment] 2021-08-05 19:31
One more comment - here is a test script function that tests the original problem.  It reads 1.5 blocks, then the next 1.5 blocks, then reads the first 3 blocks all at once.  The third read should be equal to the concat of the first two.

    def test_partial_block_reads_by_uutc(self):
    
        start = int(self.start_time)
        end = int(start + (1.5 * 1e6))
        data1 = self.ms.read_ts_channels_uutc(self.ts_channel, [start, end])
        
        start = int(self.start_time + (1.5 * 1e6))
        end = int(self.start_time + (3.0 * 1e6))
        data2 = self.ms.read_ts_channels_uutc(self.ts_channel, [start, end])
        
        start = int(self.start_time)
        end = int(start + (3.0 * 1e6))
        data_e = self.ms.read_ts_channels_uutc(self.ts_channel, [start, end])
        
        data_a = np.hstack((data1, data2))
        data_diff = data_e - data_a
       
        self.assertEqual(np.all((data_diff == 0)), True)

**Closed as completed** 2023-09-12 08:04 UTC
