### ISSUE TITLE
MEF file reading

### ISSUE THREAD

**Issue by nelagri** [msel-source/pymef#12] opened 2019-06-14 11:44 UTC
Hello,

I encountered another poblem while I was using Pymef library. I tried to store this signal, which consits of three segments of sine waves, to a MEF file:

![original](https://user-images.githubusercontent.com/7555979/59506030-7c716680-8ea7-11e9-8c56-cd9e0ad6fd0e.png)

When I want Pymef to read the whole signal (using the function _read_ts_channels_uutc_), the last segment is not returned, i. e. the result looks like this:

![uutc](https://user-images.githubusercontent.com/7555979/59506465-92cbf200-8ea8-11e9-8cda-8f3718653538.png)

Let me denote that the file contains data of all three segments. The funny thing is that if I save e. g. 4 segments-long signal, all segments are correctly read:

![uutc_4seg](https://user-images.githubusercontent.com/7555979/59506794-81371a00-8ea9-11e9-82d3-c879c8e2da86.png)

Do you what is the cause of this inconvenience? Thank you very much for your reply.

Nela

P. S. Can I have a question, why the function _read_ts_channels_sample_ returns data without gaps? I read the note about this behaviour in your documentation, but I cannot find out any advantage of this feature. Thank your for your reply.

**Comment by cimbi** [comment] 2019-06-14 15:32
Hi Nela,
the bug was introduced with one of the last commits (1f6305c174490f868ab44881edb83fdcdfd83ce7) and it was an edge artifact when reading multiple of 10 samples I think. @dancrepeau can you confirm this is the same bug? What version of pymef are you using? It should be fixed in the latest version (v.1.0.6). But it is possible you have come across something new.

As for your other question: reading by samples does not take into account the gaps mainly for signal processing. Some processing tools cannot deal with NaNs in the signal. It would also require quite a bit of additional logic to build into pymef. This might change in the future if users need this feature.

**Comment by cimbi** [comment] 2019-07-16 07:45
Nela, could you send me the code you are using to read the data back?

**Comment by nelagri** [comment] 2019-07-16 08:49
Of course, here it is.
[reader_example.zip](https://github.com/msel-source/pymef/files/3396150/reader_example.zip)

**Comment by cimbi** [comment] 2019-07-16 10:35
Found the problem. The problem is in the writer code from #11 in how you calculate the start sample for next segments. You add the NaNs to the sample count. Just create a variable start_sample=0 before the while loop and in the try statement do:
`
start_sample += len(raw_data)
`
After that the read_ts_channel_sample works fine.

**Closed as completed** 2019-07-16 10:36 UTC
